/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package day17

import org.scalatest.{FunSuite, Matchers}
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class MainSuite extends FunSuite with Matchers {
  val board = Main.parse("""x=495, y=2..7
                           |y=7, x=495..501
                           |x=501, y=3..7
                           |x=498, y=2..4
                           |x=506, y=1..2
                           |x=498, y=10..13
                           |x=504, y=10..13
                           |y=13, x=498..504""".stripMargin.lines.toList)

  val bucketInBucketBoard = Main.parse("""x=495, y=1..7
                                         |y=7, x=495..505
                                         |x=505, y=2..7
                                         |x=498, y=3..5
                                         |x=502, y=3..5
                                         |y=5, x=498..502
                                         |y=9, x=494..506
                                         |""".stripMargin.lines.toList)

  test("run") {
    val str = Main.toString(Main.run(board.updated(Point(500,0), Reachable)))
    println(str)
    str should be (""".....|......
                     |.....|.....#
                     |#..#||||...#
                     |#..#~~#|....
                     |#..#~~#|....
                     |#~~~~~#|....
                     |#~~~~~#|....
                     |#######|....
                     |.......|....
                     |..|||||||||.
                     |..|#~~~~~#|.
                     |..|#~~~~~#|.
                     |..|#~~~~~#|.
                     |..|#######|.""".stripMargin)
  }

  test("bucket-in-bucket run") {
    val str = Main.toString(Main.run(bucketInBucketBoard.updated(Point(500,0), Reachable)))
    println(str)
    str should be (""".......|.......
                     |..#|||||||||||.
                     |..#~~~~~~~~~#|.
                     |..#~~#~~~#~~#|.
                     |..#~~#~~~#~~#|.
                     |..#~~#####~~#|.
                     |..#~~~~~~~~~#|.
                     |..###########|.
                     ||||||||||||||||
                     ||#############|""".stripMargin)
  }

}
