/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package day06

import org.scalatest.{FunSuite, Matchers}
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class MainSuite extends FunSuite with Matchers {
  val points = List(Point(1, 1), Point(1, 6), Point(8, 3),
                    Point(3, 4), Point(5, 5), Point(8, 9))
  test("regions") {
    Main.regions(points)(Point(5,5)).length should be (17)
  }

  test("totalDistances") {
    Main.totalDistances(points)(Point(4,3)) should be (30)
    Main.totalDistances(points)(Point(1,5)) should be (32)
  }
}
