/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package day20

import org.scalatest.{FunSuite, Matchers}
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class MainSuite extends FunSuite with Matchers {
  test("follow simple") {
    Main.follow("N") should be (Map(Point(0,0) -> Set(Point(0,1)), Point(0,1) -> Set(Point(0,0))))
  }
}
