/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package day05

import org.scalatest.{FunSuite, Matchers}
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class MainSuite extends FunSuite with Matchers {
  List(
    ("", ""),
    ("a", "a"),
    ("aa", "aa"),
    ("aA", ""),
    ("aAb", "b"),
    ("baA", "b"),
    ("baAb", "bb"),
    ("baAB", ""),
    ("dabAcCaCBAcCcaDA", "dabCBAcaDA"),
  ).foreach { case (input, output) =>
    test(s"""react($input) should be "$output"""") {
      Main.react(input) should be (output)
    }
  }

  test("ans2") {
    Main.ans2("dabAcCaCBAcCcaDA") should be (('c', "daDA"))
  }
}
