/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package day14

import org.scalatest.{FunSuite, Matchers}
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class MainSuite extends FunSuite with Matchers {
  test("") {
  }
}
