/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package day14

import org.scalatest.{FunSuite, Matchers}
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class MainSuite extends FunSuite with Matchers {
  test("ans1") {
    Main.ans1(9)._2 should be ("5158916779")
    Main.ans1(2018)._2 should be ("5941429882")
  }

  test("ans2") {
    Main.ans2("51589") should be (9)
    Main.ans2("59414") should be (2018)
  }
}
