/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package day11

import day11.Main.Point
import org.scalatest.{FunSuite, Matchers}
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class MainSuite extends FunSuite with Matchers {
  test("hundredsDigit") {
    Main.hundredsDigit(1) should be (0)
    Main.hundredsDigit(100) should be (1)
    Main.hundredsDigit(1234) should be (2)
  }

  List(
    (Point(3,5), 8)
  ).foreach { case (coord, sn) =>
    test(s"powerLevel($coord, $sn}") {
      Main.powerLevel(coord, sn) should be (4)
    }
  }
}
