/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package day14

// ugh, custom mutable data structure
case class Recipe(data: Int) {
  var next: Recipe = this
  var prev: Recipe = this

  def insertAfter(a: Int): Unit = {
    val n = Recipe(a)
    n.next = this.next
    n.prev = this
    this.next = n
    n.next.prev = n
  }

  def toRight(i: Int): Recipe =
    (0 to i).foldLeft(this){ case (r,_) => r.next }

  def toLeft(i: Int): Recipe =
    (0 to i).foldLeft(this){ case (r,_) => r.prev }
}

case class State()

object Main {
  def main(args: Array[String]): Unit = {

  }
}
