/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package day09

import org.scalatest.{FunSuite, Matchers}
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class MainSuite extends FunSuite with Matchers {
  List(
    (9, 25, 32),
    (10, 1618, 8317),
    (13, 7999, 146373),
    (17, 1104, 2720), // The puzzle said this should be 2764, but...
    (21, 6111, 54718),
    (30, 5807, 37305),
  ).foreach { case (players, lastMarble, highScore) =>
    test (s"play($players, $lastMarble) should be $highScore") {
      Main.play(players, lastMarble) should be (highScore)
    }
  }
}
